TOP=..
include $(TOP)/configure/CONFIG
include $(PYDEVSUP)/configure/CONFIG_PY

PY += __init__.py
PY += test_support.py
PY += device_generator.py
PY += magnet_generators.py

include $(TOP)/configure/RULES
include $(PYDEVSUP)/configure/RULES_PY
