TOP=..
include $(TOP)/configure/CONFIG
include $(PYDEVSUP)/configure/CONFIG_PY

PY += __init__.py
PY += test_class_support.py
PY += autonomous_emittance.py
PY += ml_emittance_scan_runner.py

include $(TOP)/configure/RULES
include $(PYDEVSUP)/configure/RULES_PY
