TOP=..
include $(TOP)/configure/CONFIG
include $(PYDEVSUP)/configure/CONFIG_PY

PY += __init__.py
PY += registry.py
PY += base.py
PY += autonomous_program.py


include $(TOP)/configure/RULES
include $(PYDEVSUP)/configure/RULES_PY
