TOP=..
include $(TOP)/configure/CONFIG
include $(PYDEVSUP)/configure/CONFIG_PY

PY += __init__.py
PY += system_checks.py
PY += system_checks_support.py


include $(TOP)/configure/RULES
include $(PYDEVSUP)/configure/RULES_PY
