TOP=..
include $(TOP)/configure/CONFIG
include $(PYDEVSUP)/configure/CONFIG_PY

PY += __init__.py
#PY += program_readiness_checks.py


include $(TOP)/configure/RULES
include $(PYDEVSUP)/configure/RULES_PY
